<?php require_once "./templates/layouts/header.phtml"; ?>

<div class="d-flex gap-5">
  <form action="nuevoVehiculo" method="POST" class="container bg-light p-5">
    <div class="row mb-3">
      <label for="patente" class="col-sm-2 col-form-label">Patente</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputPatente" name="patente" required>
      </div>
    </div>
    <div class="row mb-3">
      <label for="modelo" class="col-sm-2 col-form-label">Modelo</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputModelo" name="modelo" required>
      </div>
    </div>
    <div class="row mb-3">
      <label for="marca" class="col-sm-2 col-form-label">Marca</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputMarca" name="marca" required>
      </div>
    </div>
    <div class="row mb-3">
      <label for="anio" class="col-sm-2 col-form-label">Año</label>
      <div class="col-sm-10">
        <input type="number" class="form-control" id="inputAnio" name="anio" required>
      </div>
    </div>
    <div class="row mb-3">
      <label for="color" class="col-sm-2 col-form-label">Color</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputColor" name="color" required>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Guardar</button>
  </form>