<?php require_once "./templates/layouts/header.phtml"; ?>

<div>
  <form class="container bg-light w-50 p-5">
    <div class="row mb-3">
      <label for="inputUsername3" class="col-sm-2 col-form-label">Username</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="inputUsername3" required>
      </div>
    </div>
    <div class="row mb-3">
      <label for="inputPassword3" class="col-sm-2 col-form-label">Password</label>
      <div class="col-sm-10">
        <input type="password" class="form-control" id="inputPassword3" required>
      </div>
    </div>
    <button type="submit" class="btn btn-primary">Log in</button>
  </form>
</div>

<?php require_once "./templates/layouts/footer.phtml"; ?>