<!doctype html>
<html lang="es">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Agencia de autos</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
  <header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary ps-3 pe-3">
      <div class="container-fluid">
        <a class="navbar-brand" href="<?= BASE_URL ?>">Agencia de autos</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>vehiculos">Vehículos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="<?= BASE_URL ?>">Alquileres</a>
            </li>
          </ul>
          <div class="d-flex justify-content-between">
            <?php if ($this->user): ?>
              <span class="navbar-text mx-lg-3 text-primary fw-bold"><?= htmlspecialchars($this->user->Usuario) ?></span>
            <?php endif; ?>
            <div>
              <?php if (!$this->user): ?>
                <a class="btn btn-primary btn-sm" href="<?= BASE_URL ?>showLogin" role="button">Log In</a>
              <?php endif; ?>
              <?php if ($this->user): ?>
                <a class="btn btn-secondary btn-sm" href="logout" role="button">Log out</a>
              <?php endif; ?>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </header>
  <main class="container mt-3">