<?php require_once "./templates/layouts/header.phtml"; ?>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <!-- <small>$category->Marca ?></small> -->
    <p>Patente: <?= $vehiculo->Patente ?></p>
    <h6 class="card-title">Modelo: <?= $vehiculo->Modelo ?></h6>
    <h6 class="card-title">Marca: <?= $vehiculo->Marca ?></h6>
    <h6 class="card-title">Año: <?= $vehiculo->Año_de_Modelo ?></h6>
    <h6 class="card-title">Color: <?= $vehiculo->Color ?></h6>
    <img class="img-thumbnail" src=" <?= $vehiculo->Imagen ?>" alt="Imagen del Vehiculo">
  </div>
  <a href="<?= BASE_URL . '/vehiculos'?>" class="card-link text-end p-3">Volver</a>
</div>
</div>

<?php require_once "./templates/layouts/footer.phtml"; ?>