<?php require_once "./templates/layouts/header.phtml"; ?>

<div class="card w-25">
  <!-- <img src=" $category->Imagen ?>" class="card-img-top" alt=" $category->Modelo?>  $category->Año_de_Modelo?>"> -->
  <div class="card-header">
    <!-- <small> $category->Marca ?></small> -->
  </div>
  <div class="card-body">
    <p>Fecha de entrega: <?= $item->Fecha_de_entrega ?></p>
    <h6 class="card-title">Fecha de vencimiento: <?= $item->Fecha_de_vencimiento ?></h6>
    <span class="badge text-bg-primary rounded-pill">$<?= $item->Precio ?></span>
  </div>
  <a href="<?= BASE_URL ?>" class="card-link text-end p-3">Volver</a>
</div>
</div>

<?php require_once "./templates/layouts/footer.phtml"; ?>