<?php require_once "./templates/layouts/formItems.phtml"; ?>

<section class="container">
  <h2>Lista de alquileres</h2>
  <ul class='list-group'>
    <?php foreach ($items as $item) : ?>
      <li class="list-group-item d-flex justify-content-between align-items-center p-4">
        <div class="ms-2 me-auto">
          <!-- <small></small> -->
          <div class="fw-bold">
            <h6>Fecha de entrega: <?= $item->Fecha_de_entrega ?> </h6>
            <h6>Fecha de vencimiento: <?= $item->Fecha_de_vencimiento ?></h6>
          </div>
          <span class="badge text-bg-primary rounded-pill">$<?= $item->Precio ?></span>
          <a class="mx-3" href="alquiler/<?= $item->ID ?>">Detalles</a>
        </div>
        <a class="btn btn-outline-success mx-3" href="editarAlquiler/<?= $item->ID ?>" role="button">Editar</a>
        <a class="btn btn-outline-danger" href="eliminarAlquiler/<?= $item->ID ?>" role="button">Eliminar</a>
      </li>
    <?php endforeach ?>
  </ul>
</section>
</div>

<?php require_once "./templates/layouts/footer.phtml"; ?>