<?php require_once "./templates/layouts/formItems.phtml"; ?>

<section class="container">
  <h2>Lista De Vehiculos</h2>
  <ul class='list-group'>
    <?php foreach ($vehiculos as $vehiculo) : ?>
      <li class="list-group-item d-flex justify-content-between align-items-center p-4">
        <div class="ms-2 me-auto">
            <!-- <small> $category->Marca ?></small> -->
            <div class="fw-bold">
              <h6>Modelo: <?= $vehiculo->Modelo ?> </h6>
              <h6>Patente: <?= $vehiculo->Patente ?></h6>
              <h6>Marca: <?= $vehiculo->Marca ?></h6>
            </div>
          </div>
          <!-- <a href="alquiler/<?= $item->ID ?>">Detalles</a> -->
        </li>
        <?php endforeach ?>
  </ul>
</section>
</div>

<?php require_once "./templates/layouts/footer.phtml"; ?>