<?php if ($editar): ?>
  <?php require_once "./templates/layouts/formEditItems.phtml"; ?>
<?php else : ?>
  <?php require_once "./templates/layouts/formItems.phtml"; ?>
<?php endif ?>

<section class="container">
  <h2>Lista de alquileres</h2>
  <ul class='list-group'>
    <?php foreach ($items as $item) : ?>
      <li class="list-group-item d-flex justify-content-between align-items-center p-4">
        <?php foreach ($categories as $category) : ?>
          <?php if ($category->ID_Vehiculo == $item->ID_Vehiculo): ?>
            <img src="<?= $category->Imagen ?>" class="w-25 flex-shrink-0 me-3" alt="<?= $category->Modelo ?> <?= $category->Año_de_Modelo ?>">
            <div class="ms-2 me-auto">
              <p class="fw-bold text-secondary"><?= $category->Marca ?></p>
            <?php endif; ?>
          <?php endforeach ?>
          <span class="badge text-bg-primary rounded-pill">$<?= $item->Precio ?></span>
            </div>
            <a class="btn btn-outline-success mx-3" href="editarAlquiler/<?= $item->ID ?>" role="button">Editar</a>
            <a class="btn btn-outline-danger" href="eliminarAlquiler/<?= $item->ID ?>" role="button">Eliminar</a>
            <a class="mx-3" href="alquiler/<?= $item->ID ?>">Detalles</a>
      </li>
    <?php endforeach ?>
  </ul>
</section>
</div>

<?php require_once "./templates/layouts/footer.phtml"; ?>