<?php require_once "./templates/layouts/header.phtml"; ?>

<?php foreach ($vehicles as $vehicle) : ?>
  <?php if ($vehicle->ID_Vehiculo == $rent->ID_Vehiculo): ?>
    <div class="d-flex flex-column align-items-center flex-lg-row bg-light py-3 rounded-1">
    <div class="d-lg-flex flex-lg-row px-4 align-items-lg-center">
      <div class="p-3" style="width: 300px;">
        <img src="<?= $vehicle->Imagen ?>" class="object-fit-cover me-3 img-fluid rounded-1" alt="<?= $vehicle->Modelo ?> <?= $vehicle->Año_de_Modelo ?>">
      </div>
        <div class="w-auto px-3">
          <h5 class="mt-0"><?= $vehicle->Marca ?> <?= $vehicle->Modelo ?> <?= $vehicle->Año_de_Modelo ?></h5>
          <p class="fw-semibold text-secondary">Fecha de entrega: <?= $rent->Fecha_de_entrega ?></p>
          <p class="fw-semibold text-secondary">Fecha de vencimiento: <?= $rent->Fecha_de_vencimiento ?></p>
          <span class="badge text-bg-primary rounded-pill">$<?= $rent->Precio ?></span>
          <a href="<?= BASE_URL ?>" class="btn btn-link p-3">Volver</a>
        </div>
      </div>
    </div>
    <?php require_once "./templates/layouts/footer.phtml"; ?>
  <?php endif; ?>
<?php endforeach ?>