<?php require_once "./templates/layouts/header.phtml"; ?>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><?=$item->Modelo?>, <?=$item->Marca?></h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">Patente: <?=$item->Patente?></h6>
    <a href="<?=BASE_URL?>" class="card-link">Volver</a>
  </div>
</div>

<?php require_once "./templates/layouts/footer.phtml"; ?>